### ISSUE TITLE
Anomaly indicator in the search results is inconsistent with the anomaly status in the measurement page

### ISSUE THREAD

**Issue by anadahz** [ooni/explorer#360] opened 2019-12-12 16:29 UTC
This example search query should list only anomalies: https://explorer.ooni.org/search?until=2019-12-12&probe_cc=CL&only=anomalies

Instead it lists measurements with `OK` status:
https://explorer.ooni.org/measurement/20191211T061838Z_AS27651_1SFSzDEdaOI7luf7GKijq5OFWLzsZW8VjaFgI0mQrenC3Z0Zqy?input=https://kids.yahoo.com/

**Comment by hellais** [comment] 2019-12-12 20:53
@anadahz can you share a screenshot?

**Comment by anadahz** [comment] 2019-12-12 21:06
![cl_anomalies](https://user-images.githubusercontent.com/4969544/70749012-2c267480-1d23-11ea-9dec-6e22cb370666.png)
![cl_kids yahoo](https://user-images.githubusercontent.com/4969544/70749013-2c267480-1d23-11ea-861f-7a4e5514c068.png)

**Comment by FedericoCeratto** [comment] 2019-12-12 23:22
For https://explorer.ooni.org/measurement/20191210T135558Z_AS14117_Z7fu65vUWmKbikKKf5djOacxXfFiXfhHktqOQExdl6TmB9dAWl?input=https://www.uber.com/ fastpath reports blocking_general = 0.5 approx

**Comment by hellais** [comment] 2019-12-13 10:12
Ok I understand now what you mean. I updated the issue title to reflect this.

I believe the `anomaly` value is determined from what is returned by the API in the listing, while the status on the page is based on client side calculation. @sarathms is this the case?

If so we should probably derive the `anomaly` value in the measurement pages from the same source as we derive the search results to ensure consistent results.

**Comment by hellais** [comment] 2019-12-13 10:14
Ah yes what @FedericoCeratto also could be relevant to this too, where the `anomaly` logic is also now computed in the fastpath and uses a somewhat different logic to what is done to determine the `anomaly` flag inside of the batch pipeline. This may also be the cause for the misalignment between the two results.

**Comment by sarathms** [comment] 2020-01-09 19:19
> I believe the anomaly value is determined from what is returned by the API in the listing, while the status on the page is based on client side calculation. @sarathms is this the case?

No. There is an additional API call to `/api/v1/measurements` before rendering the measurement page to fetch the `anomaly`, `error` and `confirmed` flags for the listing. We use this to 'theme' the page as an anomaly or confirmed measurement.

While the reported issue seems to be fixed now, I discovered a different variant where the search listing says it is an anomaly, and the page begins to render it as an anomaly because the `measurement.anomaly` flag is set to `true`, but `measurement.test_keys.blocking` is `false`. But now, this throws an exception because an anomaly page expects the blocking flag to have a reason to show it to the user.

![image.png](https://images.zenhubusercontent.com/5defc00b8c6ab2dae53692c4/d0c9ff22-07d2-4a60-906c-303569bb80ae)
Search listing from API:
http://api.ooni.io/api/v1/measurements?report_id=20200109T172742Z_AS22773_KRKN4WK5UyhnPLoxPQZ4KflEbdJ3DlPxKil231pbiRnR5WvgL5
Full measurement:
https://api.ooni.io/api/v1/measurement/temp-fid-003ce401ad2d9f4e11bb6a0cbf7fda61

**Comment by FedericoCeratto** [comment] 2020-01-09 21:03
Update: this has been discussed; we are going to fix this as part of https://github.com/ooni/pipeline/issues/278

**Comment by hellais** [comment] 2020-01-16 14:38
Another possibly related case is when the error/failure status is inconsistent between the search and the measurement page, as is for: https://explorer.ooni.org/measurement/20200115T175456Z_AS16135_02e6K7rm4O8Vlx6203sfZrQ8uh9wbE7UKlg5Rkag4TGKxI5efk?input=https://wikipedia.org

**Comment by hellais** [comment] 2020-02-04 15:37
An initial remediation to the previous problem has been done. We have created a new issue to track future work.

**Closed** 2020-03-16 15:20 UTC
Labels: bug, effort/M, priority/medium
