### ISSUE TITLE
Wrong list of measurements for domain set in query

### ISSUE THREAD

**Issue by anadahz** [ooni/explorer#359] opened 2019-12-10 15:02 UTC
## Expected Behavior
Explorer should list measurements with the correct domain set in query.

## Actual Behavior
Explorer lists unrelated measurements with the correct domain set in query.

## Steps to Reproduce the Problem

  1. Search for the domain `google.com` in explorer (Query: http://explorer.ooni.org/search?until=2019-12-09&domain=google.com&probe_cc=CA&test_name=web_connectivity&since=2019-10-01)

**Comment by hellais** [comment] 2019-12-11 16:48
This has been fixed in: https://github.com/ooni/api/pull/144 (and is duplicate of: https://github.com/ooni/api/issues/142)

**Closed by hellais** 2019-12-11 16:48 UTC
