### ISSUE TITLE
Vanilla Tor measurements missing from IR country page

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#256] opened 2019-08-14 14:58 UTC
Many Vanilla Tor measurements have been collected from Iran over the last years (which we discuss and analyze in our relevant research report: https://ooni.io/post/iran-internet-censorship/) but they're missing from the Iranian country page on OONI Explorer. See:

![ir-no-vanilla-tor](https://user-images.githubusercontent.com/8290574/63031671-adc0df80-beb4-11e9-9612-80419dff95b3.png)

**Comment by hellais** [comment] 2019-11-18 08:16
This is because we only present measurements from the last 30 days inside of that section of the country page. It appears that the vanilla tor test has not been run in the last 30 days in Iran and hence it's not appearing there.

I am closing this as not a bug.

**Closed by hellais** 2019-11-18 08:16 UTC
