### ISSUE TITLE
Capitalize the initial letters of test classes displayed in measurement coverage graph

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#269] opened 2019-08-23 13:56 UTC
The Measurement Coverage by Test Class graph available in all OONI Explorer country pages includes legends which explain each OONI Probe test class.

However, when hovering over the bars within the graph, the test class names (e.g. Websites) are written in all lower-case, which is inconsistent with (a) the word Networks (also displayed in the black pop-up labels and which is capitalized), and (b) the way each test class name is presented within the legends (where the first letter is in caps). 

For consistency (and presentation) purposes, please replace "im", "websites", "performance", "middleboxes", and "circumvention" with "IM", "Websites", "Performance", Middleboxes", and "Circumvention".

**Comment by hellais** [comment] 2019-08-29 10:15
I think this is a duplicate of https://github.com/ooni/explorer/issues/268

**Closed** 2019-09-02 15:54 UTC
