### ISSUE TITLE
Create domain-specific views

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#273] opened 2019-08-24 17:46 UTC
Community members proposed that we include domain-specific views that aggregate information across countries, so that you're able to easily compare the blocking of a specific domain across countries. 

It would also be great to show more granularity with regards to domain-specific measurements.

This could potentially be featured as a separate top navbar within OONI Explorer.

**Comment by hellais** [comment] 2019-08-29 10:19
This is a duplicate of https://github.com/ooni/explorer/issues/67

**Closed** 2019-08-29 10:19 UTC
Labels: duplicate
