### ISSUE TITLE
Fix bug displaying middlebox measurements as "OK" (when they should be anomalous)

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#617] opened 2021-10-09 13:21 UTC
We've been aware that some bug wrongly displays some Web Connectivity + RiseupVPN measurements as "OK" on OONI Explorer, when in fact they should be displayed as "anomalous" (based on the raw data).

A community member just discovered that a similar bug appears to be affecting middlebox measurements too: https://explorer.ooni.org/measurement/20211004T034903Z_httpinvalidrequestline_TM_20661_n1_8KI06VoG3SUN3Evl

This measurements is marked as "no middlebox detected", but should be marked as anomalous (no response was received).

**Comment by sarathms** [comment] 2021-11-10 02:14
I don't think this can be fixed at the Explorer end. The underlying [API call response](https://api.ooni.io/api/v1/measurement_meta?report_id=20211004T034903Z_httpinvalidrequestline_TM_20661_n1_8KI06VoG3SUN3Evl&full=true) for this measurement states that this is not an anomaly. Looking at the raw measurement, it seems like the probe itself determined there is no tampering (`tampering: false`). 

Maybe @FedericoCeratto or @bassosimone can confirm this.
```
{
  "anomaly": false, 
  "confirmed": false, 
  "failure": false, 
  "input": null, 
  "measurement_start_time": "2021-10-04T03:49:02Z", 
  "measurement_uid": "20211004034903.705790_TM_httpinvalidrequestline_1170a5ba4a84a500", 
  "probe_asn": 20661, 
  "probe_cc": "TM", 
  "raw_measurement": "{\"annotations\":{\"engine_name\":\"ooniprobe-engine\",\"engine_version\":\"3.10.0-beta.3\",\"flavor\":\"stableFull\",\"network_type\":\"wifi\",\"platform\":\"android\"},\"data_format_version\":\"0.2.0\",\"input\":null,\"measurement_start_time\":\"2021-10-04 03:49:02\",\"probe_asn\":\"AS20661\",\"probe_cc\":\"TM\",\"probe_ip\":\"127.0.0.1\",\"probe_network_name\":\"State Company of Electro Communications Turkmentelecom\",\"report_id\":\"20211004T034903Z_httpinvalidrequestline_TM_20661_n1_8KI06VoG3SUN3Evl\",\"resolver_asn\":\"AS0\",\"resolver_ip\":\"127.0.0.1\",\"resolver_network_name\":\"\",\"software_name\":\"ooniprobe-android\",\"software_version\":\"3.3.0\",\"test_helpers\":{\"backend\":\"37.218.241.93\"},\"test_keys\":{\"failure_list\":[\"connection_refused\",\"connection_refused\",\"connection_refused\",\"connection_refused\",\"connection_refused\"],\"received\":[\"\",\"\",\"\",\"\",\"\"],\"sent\":[\"\",\"\",\"\",\"\",\"\"],\"tampering_list\":[false,false,false,false,false],\"tampering\":false},\"test_name\":\"http_invalid_request_line\",\"test_runtime\":0.047318961,\"test_start_time\":\"2021-10-04 03:49:01\",\"test_version\":\"0.2.0\"}\n", 
  "report_id": "20211004T034903Z_httpinvalidrequestline_TM_20661_n1_8KI06VoG3SUN3Evl", 
  "scores": "{\"blocking_general\":0.0,\"blocking_global\":0.0,\"blocking_country\":0.0,\"blocking_isp\":0.0,\"blocking_local\":0.0}", 
  "test_name": "http_invalid_request_line", 
  "test_start_time": "2021-10-04T03:49:01Z"
}

```

**Comment by sarathms** [comment] 2021-11-10 02:19
The relevant [API call when searching](https://api.ooni.io/api/v1/measurements?probe_cc=TM&probe_asn=AS20661&test_name=http_invalid_request_line&since=2021-10-04&until=2021-10-05&limit=50) for this measurement also says it is accessible.

**Comment by hellais** [comment] 2021-11-24 16:38
The measurement linked above shows that there was a connection_refused error when attempting to connect to the OONI test helper. This may be caused by either the blocking of the service or the test helper service being down.

I think this can be closed as it's not a bug.

**Closed by hellais** 2021-11-24 16:38 UTC
Labels: bug
