### ISSUE TITLE
Enable users to report false positives

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#647] opened 2021-12-21 16:03 UTC
During the OONI Partner Training 2021, participants mentioned that it would be great if OONI Explorer provided a feature that enabled users to report false positives.

We already are planning on doing this. This would help ensure better data characterization and analysis.

**Comment by hellais** [comment] 2022-01-31 09:11
This is a duplicate of: https://github.com/ooni/probe/issues/872

**Closed by hellais** 2022-01-31 09:11 UTC
Labels: duplicate, enhancement, user feedback, partner training 2021
