### ISSUE TITLE
Listing/Filtering of results show Accessible, but measurement page and data shows Anomaly

### ISSUE THREAD

**Issue by kaerumy** [ooni/explorer#402] opened 2020-02-17 23:20 UTC
## Expected Behavior

Measurements that detect Anomaly should also be found and listed as such in Search page

## Actual Behavior

- Filtering on Anomalies will not return measurements that are detected as anomaly.
- Search results of accessible websites, which are actually marked as anomaly by measurement data and on measurement page.

## Steps to Reproduce the Problem

  1. Search for site with anomaly  https://explorer.ooni.org/search?until=2020-02-19&domain=www.literotica.com&probe_cc=MY
  2. Listing will show that site is accessible for recent tests 
![image](https://user-images.githubusercontent.com/1060743/74691720-e1434480-521e-11ea-91b7-0c712cb5419d.png)
  3. When clicking on measurement report, it is actually detected as anomaly https://explorer.ooni.org/measurement/20200217T225031Z_AS4818_VUPpBQ23oNyMWtKl4wVyYqvdfSUFQ4qsXZe3I9TdEfran1ZArd?input=https://www.literotica.com 
![image](https://user-images.githubusercontent.com/1060743/74691754-03d55d80-521f-11ea-860c-154931056dd0.png)

## Specifications

  - Version: 2.06
  - Platform: Linux
  - Subsystem: Firefox 73.0

**Comment by hellais** [comment] 2020-02-18 09:45
Thanks for reporting this issue, we are aware of this and it has been first reported here: https://github.com/ooni/explorer/issues/360.

I am going to close this issue as duplicate of https://github.com/ooni/explorer/issues/360.

**Closed by hellais** 2020-02-18 09:45 UTC
