### ISSUE TITLE
Lowercase of country name shows unexpected results

### ISSUE THREAD

**Issue by anadahz** [ooni/explorer#331] opened 2019-10-03 10:32 UTC
The lowercase version of a country name in Explorer's URL is bringing out unexpected results:
`Since 1/1/1970, OONI Probe users in have collected 0 measurements from 0 local networks.`

However the flag of the country is correct.

## Steps to Reproduce the Problem

Visit Explorer's county profile with country's name in lowercase (eg. https://explorer.ooni.org/country/se)

## Expected behavior

Redirect to the correct country profile or present a 404.

**Comment by hellais** [comment] 2019-11-18 09:05
This is a duplicate of: https://github.com/ooni/explorer/issues/164

**Closed by hellais** 2019-11-18 09:05 UTC
