### ISSUE TITLE
Some entries in search result list are labeled "accessible" incorrectly

### ISSUE THREAD

**Issue by ksangchan** [ooni/explorer#399] opened 2020-02-12 21:52 UTC
<- Remember to label this issue accordly (bug, feature, help wanted, etc). And remove any information that does not fit the issue you are submitting.  -> 

## Expected Behavior
1. Go to https://explorer.ooni.org/search?until=2020-02-12&probe_cc=CN&since=2020-02-05&test_name=web_connectivity
2. Find zh.wikipedia.org item
3. On the list it should show "Anomaly"
4. Click on the item, which opens https://explorer.ooni.org/measurement/20200211T065336Z_AS4134_4M0eNXqQCp1mrHumzmR73pHhLRMyVh1dAc4VYcoICjBAkqjxlZ?input=https://zh.wikipedia.org/ , it shows "Anomaly"

## Actual Behavior
1. Go to https://explorer.ooni.org/search?until=2020-02-12&probe_cc=CN&since=2020-02-05&test_name=web_connectivity
2. Find zh.wikipedia.org item
3. On the result  list it shows "Accessible"
4. Click on the item, which opens https://explorer.ooni.org/measurement/20200211T065336Z_AS4134_4M0eNXqQCp1mrHumzmR73pHhLRMyVh1dAc4VYcoICjBAkqjxlZ?input=https://zh.wikipedia.org/ , it shows "Anomaly"

![Screenshot_20200212_164405](https://user-images.githubusercontent.com/52733452/74381345-3ca5aa80-4db9-11ea-94e0-6f055d55cffd.png)

## Note

I have found https://github.com/ooni/explorer/issues/113 , which should have been fixed, so I opened a new issue.

## Specifications

  - Version: Firefox 72
  - Platform: Linux
  - Subsystem:

**Comment by hellais** [comment] 2020-02-14 13:31
Hi, thanks for reporting this issue.

This is being caused by the fact that we use different logic to render the measurement details view vs the result listing.

Moreover we have two different pipelines that are being used to calculate recent measurements (fastpath) vs old measurement (batch pipeline), which are also using slightly different logic.

This has been previous reported in: https://github.com/ooni/explorer/issues/360.

Our long term plan is to do this: https://github.com/ooni/backend/issues/326.

I am going to close this issue as duplicate.

**Closed by hellais** 2020-02-14 13:31 UTC
Labels: duplicate
