### ISSUE TITLE
Fix link to measurements in the 500 error page

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#255] opened 2019-08-14 14:50 UTC
I was exploring the Iran country page and then suddenly it redirected to this page:

![redirect-error](https://user-images.githubusercontent.com/8290574/63030876-638b2e80-beb3-11e9-8ba0-56bd59a81494.png)

I then clicked on the "exploring some measurements" link, but it seems that the wrong link has been linked, since it points to: https://explorer-beta.ooni.io/countried instead of https://explorer-beta.ooni.io/countries

Edit this link (https://explorer-beta.ooni.io/countried) so that it has "s" instead of "d" in the word "countries".

**Comment by sarathms** [comment] 2019-09-19 14:03
The link `href` was fixed in #251 but now the problem is remains but in a different way. Clicking the link, takes you to the right URL, but still shows the error page. Doesn't happen for **Page Not Found** (404) error pages.

**Comment by sarathms** [comment] 2019-09-25 15:17
Closing this in favor of a more specific bug opened here #324

**Closed by sarathms** 2019-09-25 15:17 UTC
Labels: bug
