### ISSUE TITLE
Site fails with 504 error.

### ISSUE THREAD

**Issue by kotenok2000** [ooni/explorer#650] opened 2022-01-13 12:37 UTC
<- Remember to label this issue accordly (bug, feature, help wanted, etc). And remove any information that does not fit the issue you are submitting.  -> 

## Expected Behavior

The request works.
## Actual Behavior
{
  "error": "504 Gateway Timeout: The connection to an upstream server timed out."
}

## Steps to Reproduce the Problem

  1. Go to https://explorer.ooni.org/country/RU#network-properties
  2. Select AS25513 from the list (it is second by count)
  3. Press any Explore more measurements link 

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by hellais** [comment] 2022-01-14 12:58
Thanks for reporting this issue. I have tried to reproduce it, but am currently unable to.

That said, we aware of transient performance issues in accessing certain database heavy API endpoints and are in the process of migrating to a new database backend to improve the situation.

I suggest we close this issue once that happens, which will be when we merge and deploy: https://github.com/ooni/api/pull/271

**Comment by kotenok2000** [comment] 2022-01-14 13:04
This request fails
https://explorer.ooni.org/search?test_name=web_connectivity&probe_cc=RU&probe_asn=25513&domain=www.deti-404.com&since=2021-12-15&until=2022-01-15

**Comment by hellais** [comment] 2022-02-07 16:19
We have since switched to a new database backend for the search queries, so these should no longer be an issue. I think we can consider this closed.

If you do still run into some queries that fail, please do let us know, either in this issue or a new one.

Thanks!

**Closed by hellais** 2022-02-07 16:19 UTC
Labels: bug, priority/medium
