### ISSUE TITLE
MAT charts don't work with large date ranges

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#678] opened 2022-02-23 17:03 UTC
When I try to create a MAT chart based on the testing of WhatsApp in Myanmar between 2016 to date (https://explorer.ooni.org/experimental/mat?probe_cc=MM&test_name=whatsapp&since=2016-01-24&until=2022-02-24&axis_x=measurement_start_day&axis_y=probe_cc), I get the following:

![broken](https://user-images.githubusercontent.com/8290574/155368974-ab69e0eb-eec8-4afc-a184-7d40710cd772.png)

Why is the chart empty/broken?

In the table below, it says `Anomaly count` = `10534`, and `Measurement count` = `20924` in this date range. 

Ideally, this would be fixed. But if we're not able to fix this by the launch (if, for example, there's some backend issue cc' @FedericoCeratto ), we should still inform the user that they should try again with a smaller date range.

**Comment by hellais** [comment] 2022-02-28 14:45
Isn't this a duplicate of: https://github.com/ooni/explorer/issues/679?

**Closed** 2024-02-26 09:28 UTC
Labels: bug, priority/low, MAT
