### ISSUE TITLE
Enable users to sort measurements by ASN

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#640] opened 2021-12-21 15:45 UTC
During the OONI Partner Training 2021, participants mentioned that it would be useful to be able to sort/group measurements by ASN (in addition to filtering measurements by ASN). This would enable comparison of results across ASNs. I remember that Vinicius also shared this feedback.

**Comment by hellais** [comment] 2022-01-31 09:06
This is a duplicate of: https://github.com/ooni/explorer/issues/598

**Closed by hellais** 2022-01-31 09:06 UTC
Labels: enhancement, user feedback, partner training 2021
