### ISSUE TITLE
Blocked websites not displayed on country pages

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#258] opened 2019-08-16 13:03 UTC
When accessing the country page of Iran (and other country pages), I cannot view the blocked sites that are meant to be listed under the Websites section. 

When landing on the IR page, the user currently views the following under the Websites section:

![ir-websites](https://user-images.githubusercontent.com/8290574/63169363-e8528580-c036-11e9-95df-8e300de4b8bf.png)

Please fix the heuristics so that the blocked sites are displayed. Thank you.

**Comment by hellais** [comment] 2019-08-16 13:06
This is in fact caused by a pipeline bug: https://github.com/ooni/pipeline/issues/214

**Comment by agrabeli** [comment] 2019-09-04 14:45
@hellais I think the pipeline bug is fixed? Can we close this ticket?

**Comment by hellais** [comment] 2019-11-18 08:31
Yes this is fixed. Closing.

**Closed by hellais** 2019-11-18 08:31 UTC
Labels: bug
