### ISSUE TITLE
Display top & most recent censorship findings per country

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#442] opened 2020-03-27 19:21 UTC
This was initially included in older OONI Explorer mocks, but due to various challenges, we weren't able to actually ship this.

I'm opening a ticket so that we can remember to do this and to brainstorm on how to display more meaningful information (than what was originally planned).

**Comment by hellais** [comment] 2020-03-30 09:23
I think this is a duplicate of: https://github.com/ooni/explorer/issues/424.

**Closed** 2020-03-30 09:23 UTC
Labels: discuss, duplicate, enhancement, user feedback
