### ISSUE TITLE
Timestamps in NDT measurements appear to be inaccurate

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#384] opened 2020-01-29 11:28 UTC
Currently it's 11:24 UTC on 29th January 2020, but the latest OONI Explorer measurements claim that they were collected several hours ahead of the current time.

For example, this measurement says that it was collected at 15:31 UTC in Russia on 29th January 2020: https://explorer.ooni.org/measurement/20200129T103231Z_AS41330_t32RbzbNqkKp4zT8vzVv66bKcrVdqD8XYTTZp8f6is0OIP8pej 

Currently though, it's 14:25 in Moscow (excluding the hypothesis that it was collected at the local timezone). 

This doesn't appear to be a problem in Web Connectivity measurements though (https://explorer.ooni.org/search?until=2020-01-30&test_name=web_connectivity) -- perhaps it's only an issue affecting NDT measurements.

**Comment by hellais** [comment] 2020-01-29 16:57
This is likely caused by a wrong system clock or by a wrong timezone on the device. I am closing this issue in favour of: https://github.com/ooni/backend/issues/308, as this is not related to OONI Explorer.

**Closed by hellais** 2020-01-29 16:57 UTC
Labels: bug
