### ISSUE TITLE
Display IM test results on OONI Explorer Search page

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#445] opened 2020-03-27 19:33 UTC
Currently, the listing of IM test results (for WhatsApp, Facebook Messenger, Telegram tests) on OONI Explorer does not display if each individual measurement is accessible or not (similarly to Web Connectivity results). 

As a result, you need to click on each measurement individually, which can be tedious.

It would be awesome if the IM test results were displayed in the Search page listing of measurements in the following ways:

1. Add green or orange on the side, similarly to Web Connectivity results for "accessible" or "anomalous"
2. Display "Accessible" or "Likely blocked" on each measurement, similarly to Web Connectivity measurements

This would probably require implementing https://github.com/ooni/explorer/issues/444 first in order to be able to filter the measurements based on their results.

**Comment by hellais** [comment] 2020-03-30 13:40
This is a duplicate of: https://github.com/ooni/explorer/issues/444

**Closed by hellais** 2020-03-30 13:40 UTC
Labels: enhancement, priority/medium
