### ISSUE TITLE
Enable users to share feedback on OONI measurements

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#435] opened 2020-03-27 18:48 UTC
Ruling out false positives in an automated way is challenging. 

Community members have proposed that we add a feature to OONI Explorer that enables users to share feedback on OONI measurements.

The specific types of feedback that they could share could include:

- Letting us know if a measurement is a false positive (assuming that they're connected to the same network in the country in question), because they're able to access the website in question

- Letting us know if a measurement is a false positive (assuming that they're connected to the same network in the country in question), due to server-side blocking

- Letting us know that a site that presented an anomaly is in fact blocked

etc...

Essentially, perhaps we could add a feature to OONI Explorer that enables community members to comment on the measurements and to share feedback that can help improve our heuristics (and presentation of results).

**Comment by hellais** [comment] 2020-03-30 09:26
I think this may be a duplicate of: https://github.com/ooni/explorer/issues/213

**Comment by agrabeli** [comment] 2020-03-30 11:01
@hellais ah yes, you're right.

**Closed** 2020-03-30 11:01 UTC
Labels: discuss, enhancement, user feedback
