### ISSUE TITLE
Add support for filtering all measurements globally based on a single URL (and, eventually, set of URLs)

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#443] opened 2020-03-27 19:24 UTC
One of the most frequently asked questions is:

"Where around the world is my site (or a site I care about) blocked?"

It would be great to add support for filtering all measurements globally in order to find results for a single URL.

I realize though that there are challenges related to implementing this, as it would require very database-heavy queries.

**Comment by hellais** [comment] 2020-03-30 13:39
This is a duplicate of this epic: https://github.com/ooni/explorer/issues/389

**Closed** 2020-03-30 13:40 UTC
Labels: duplicate, effort/XL, enhancement
