### ISSUE TITLE
Link to measurements based on inserted input (MAT)

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#672] opened 2022-02-23 16:17 UTC
When a user filters the MAT based on a specific URL (e.g. `https://www.facebook.com/`), they can access the measurements by clicking "View measurements" in the generated chart (https://explorer.ooni.org/experimental/mat?probe_cc=DZ&test_name=web_connectivity&input=https%3A%2F%2Fwww.facebook.com%2F&since=2022-01-24&until=2022-02-24&axis_x=measurement_start_day&axis_y=probe_cc):

![view-ms](https://user-images.githubusercontent.com/8290574/155360001-f2b05013-d05e-42e4-9fdc-08286eab041e.png)

However, these measurements don't pertain to the specific website requested (`https://www.facebook.com`), but to generic Web Connectivity measurements from that country: https://explorer.ooni.org/search?since=2022-02-16&until=2022-02-17&probe_cc=DZ&test_name=web_connectivity&input=https%3A%2F%2Fwww.facebook.com%2F&failure=false

Is this because on the MAT we filter by URL, whereas on OONI Explorer Search we filter by domain?

I guess this is another reason why we should prioritize https://github.com/ooni/explorer/issues/664. 

@FedericoCeratto Does this require backend changes in the aggregation API to filter by domain (instead of URL)? If so, how feasible are these changes in the short-term?

**Comment by hellais** [comment] 2022-02-23 17:28
This is a duplicate of: https://github.com/ooni/explorer/issues/655

**Closed by hellais** 2022-02-23 17:28 UTC
Labels: enhancement, priority/high, MAT
