### ISSUE TITLE
Website categorized as MILX appears in search results for LGBTQ+ category (OONI Search)

### ISSUE THREAD

**Issue by rayasharbain** [ooni/explorer#773] opened 2022-07-26 13:50 UTC
I believe this is a bug: a website that is listed as MILX in the [Jordan test list](https://github.com/citizenlab/test-lists/blob/master/lists/jo.csv) appears in OONI Search when filtering through websites in the LGBTQ+ category (this website specifically: https://www.moqawama.org/).

## Steps to Reproduce the Problem

  1. Go to: https://explorer.ooni.org/search
  2. Country filter: `Jordan`; Website Categories filter: `LGBTQ+`
  3. Find `https://www.moqawama.org/`
  4. Find URL in Jordan test list: https://github.com/citizenlab/test-lists/blob/master/lists/jo.csv

**Comment by majakomel** [comment] 2022-10-31 18:07
I will close this issue since I cannot reproduce it anymore, but if the issue appears again please let us know about it @rayasharbain. Thanks for reporting!

**Closed by majakomel** 2022-10-31 18:07 UTC
